services:
  # Web Service
  - type: web
    name: vat-verification-platform
    runtime: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DB_SCHEMA
        value: vat_verification
      # Stripe Keys (set manually in Render dashboard)
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      # Email Configuration (set manually)
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      # API Keys (set manually)
      - key: VIES_API_KEY
        sync: false
      - key: HANDELSREGISTER_API_KEY
        sync: false
      - key: OPENCORPORATES_API_KEY
        sync: false
      - key: SANCTIONS_API_KEY
        sync: false

# Note: You need to manually create the schema in your existing PostgreSQL database
# Connect to your database and run: CREATE SCHEMA IF NOT EXISTS vat_verification;
