"""Add email threading fields (in_reply_to, references) and trust_level

Revision ID: 4d68551a0bb5
Revises: 7b1be3569a24
Create Date: 2025-11-11 21:04:48.464824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d68551a0bb5'
down_revision = '7b1be3569a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем ENUM тип для trust_levels
    op.execute("CREATE TYPE vat_verification.trust_levels AS ENUM ('low', 'medium', 'high', 'vip')")
    
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alerts_created_at')
        batch_op.create_index(batch_op.f('ix_vat_verification_alerts_created_at'), ['created_at'], unique=False)
        batch_op.drop_constraint('alerts_check_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'verification_checks', ['check_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.drop_index('ix_check_results_created_at')
        batch_op.drop_index('ix_check_results_service_name')
        batch_op.create_index(batch_op.f('ix_vat_verification_check_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_verification_check_results_service_name'), ['service_name'], unique=False)
        batch_op.drop_constraint('check_results_check_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'verification_checks', ['check_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index('ix_companies_user_id')
        batch_op.drop_index('ix_companies_vat_number')
        batch_op.create_index(batch_op.f('ix_vat_verification_companies_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_verification_companies_vat_number'), ['vat_number'], unique=False)
        batch_op.drop_constraint('companies_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.drop_index('ix_counterparties_company_name')
        batch_op.drop_index('ix_counterparties_user_id')
        batch_op.create_index(batch_op.f('ix_vat_verification_counterparties_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_verification_counterparties_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_verification_counterparties_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_verification_counterparties_vat_number'), ['vat_number'], unique=False)
        batch_op.drop_constraint('counterparties_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('known_counterparty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trust_level', sa.Enum('low', 'medium', 'high', 'vip', name='trust_levels', schema='vat_verification'), nullable=True))

    with op.batch_alter_table('mail_account', schema=None) as batch_op:
        batch_op.alter_column('provider',
               existing_type=postgresql.ENUM('gmail', 'outlook', 'imap', name='provider_types'),
               type_=sa.Enum('gmail', 'outlook', 'imap', name='provider_types', schema='vat_verification'),
               existing_nullable=False)
        batch_op.drop_constraint('mail_account_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('mail_draft', schema=None) as batch_op:
        batch_op.alter_column('suggested_by',
               existing_type=postgresql.ENUM('assistant', 'rule', 'manual', name='suggested_by_types'),
               type_=sa.Enum('assistant', 'rule', 'manual', name='suggested_by_types', schema='vat_verification'),
               existing_nullable=True)
        batch_op.drop_constraint('mail_draft_account_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('mail_draft_message_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'mail_account', ['account_id'], ['id'], referent_schema='vat_verification')
        batch_op.create_foreign_key(None, 'mail_message', ['message_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('mail_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_reply_to', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('references', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('new', 'scanned', 'drafted', 'sent', 'quarantined', 'skipped', name='status_types'),
               type_=sa.Enum('new', 'scanned', 'drafted', 'sent', 'quarantined', 'skipped', name='status_types', schema='vat_verification'),
               existing_nullable=True)
        batch_op.drop_constraint('mail_message_account_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('mail_message_counterparty_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'mail_account', ['account_id'], ['id'], referent_schema='vat_verification')
        batch_op.create_foreign_key(None, 'known_counterparty', ['counterparty_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('mail_rule', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=postgresql.ENUM('auto_reply', 'draft', 'quarantine', 'ignore', name='action_types'),
               type_=sa.Enum('auto_reply', 'draft', 'quarantine', 'ignore', name='action_types', schema='vat_verification'),
               existing_nullable=True)

    with op.batch_alter_table('osint_findings', schema=None) as batch_op:
        batch_op.drop_index('ix_osint_findings_created_at')
        batch_op.drop_index('ix_osint_findings_scan_id')
        batch_op.create_index(batch_op.f('ix_vat_verification_osint_findings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_verification_osint_findings_scan_id'), ['scan_id'], unique=False)
        batch_op.drop_constraint('osint_findings_scan_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'osint_scans', ['scan_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('osint_scans', schema=None) as batch_op:
        batch_op.drop_index('ix_osint_scans_created_at')
        batch_op.drop_index('ix_osint_scans_domain')
        batch_op.drop_index('ix_osint_scans_email')
        batch_op.create_index(batch_op.f('ix_vat_verification_osint_scans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_verification_osint_scans_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_verification_osint_scans_email'), ['email'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_created_at')
        batch_op.drop_index('ix_payments_status')
        batch_op.create_index(batch_op.f('ix_vat_verification_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_verification_payments_status'), ['status'], unique=False)
        batch_op.drop_constraint('payments_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('payments_subscription_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='vat_verification')
        batch_op.create_foreign_key(None, 'subscriptions', ['subscription_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('scan_report', schema=None) as batch_op:
        batch_op.alter_column('verdict',
               existing_type=postgresql.ENUM('safe', 'suspicious', 'malicious', name='verdict_types'),
               type_=sa.Enum('safe', 'suspicious', 'malicious', name='verdict_types', schema='vat_verification'),
               existing_nullable=False)
        batch_op.drop_constraint('scan_report_message_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'mail_message', ['message_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_subscriptions_plan')
        batch_op.drop_index('ix_subscriptions_status')
        batch_op.create_index(batch_op.f('ix_vat_verification_subscriptions_plan'), ['plan'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_verification_subscriptions_status'), ['status'], unique=False)
        batch_op.drop_constraint('subscriptions_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_created_at')
        batch_op.drop_index('ix_users_email')
        batch_op.create_index(batch_op.f('ix_vat_verification_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_verification_users_email'), ['email'], unique=True)

    with op.batch_alter_table('verification_checks', schema=None) as batch_op:
        batch_op.drop_index('ix_verification_checks_check_date')
        batch_op.drop_index('ix_verification_checks_user_id')
        batch_op.create_index(batch_op.f('ix_vat_verification_verification_checks_check_date'), ['check_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_verification_verification_checks_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('fk_verification_checks_user_id', type_='foreignkey')
        batch_op.drop_constraint('verification_checks_counterparty_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('verification_checks_company_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], referent_schema='vat_verification')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='vat_verification')
        batch_op.create_foreign_key(None, 'counterparties', ['counterparty_id'], ['id'], referent_schema='vat_verification')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_checks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('verification_checks_company_id_fkey', 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key('verification_checks_counterparty_id_fkey', 'counterparties', ['counterparty_id'], ['id'])
        batch_op.create_foreign_key('fk_verification_checks_user_id', 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_vat_verification_verification_checks_user_id'))
        batch_op.drop_index(batch_op.f('ix_vat_verification_verification_checks_check_date'))
        batch_op.create_index('ix_verification_checks_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_verification_checks_check_date', ['check_date'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vat_verification_users_email'))
        batch_op.drop_index(batch_op.f('ix_vat_verification_users_created_at'))
        batch_op.create_index('ix_users_email', ['email'], unique=True)
        batch_op.create_index('ix_users_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('subscriptions_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_vat_verification_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_vat_verification_subscriptions_plan'))
        batch_op.create_index('ix_subscriptions_status', ['status'], unique=False)
        batch_op.create_index('ix_subscriptions_plan', ['plan'], unique=False)

    with op.batch_alter_table('scan_report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('scan_report_message_id_fkey', 'mail_message', ['message_id'], ['id'])
        batch_op.alter_column('verdict',
               existing_type=sa.Enum('safe', 'suspicious', 'malicious', name='verdict_types', schema='vat_verification'),
               type_=postgresql.ENUM('safe', 'suspicious', 'malicious', name='verdict_types'),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payments_subscription_id_fkey', 'subscriptions', ['subscription_id'], ['id'])
        batch_op.create_foreign_key('payments_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_vat_verification_payments_status'))
        batch_op.drop_index(batch_op.f('ix_vat_verification_payments_created_at'))
        batch_op.create_index('ix_payments_status', ['status'], unique=False)
        batch_op.create_index('ix_payments_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('osint_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vat_verification_osint_scans_email'))
        batch_op.drop_index(batch_op.f('ix_vat_verification_osint_scans_domain'))
        batch_op.drop_index(batch_op.f('ix_vat_verification_osint_scans_created_at'))
        batch_op.create_index('ix_osint_scans_email', ['email'], unique=False)
        batch_op.create_index('ix_osint_scans_domain', ['domain'], unique=False)
        batch_op.create_index('ix_osint_scans_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('osint_findings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('osint_findings_scan_id_fkey', 'osint_scans', ['scan_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_vat_verification_osint_findings_scan_id'))
        batch_op.drop_index(batch_op.f('ix_vat_verification_osint_findings_created_at'))
        batch_op.create_index('ix_osint_findings_scan_id', ['scan_id'], unique=False)
        batch_op.create_index('ix_osint_findings_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('mail_rule', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.Enum('auto_reply', 'draft', 'quarantine', 'ignore', name='action_types', schema='vat_verification'),
               type_=postgresql.ENUM('auto_reply', 'draft', 'quarantine', 'ignore', name='action_types'),
               existing_nullable=True)

    with op.batch_alter_table('mail_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('mail_message_counterparty_id_fkey', 'known_counterparty', ['counterparty_id'], ['id'])
        batch_op.create_foreign_key('mail_message_account_id_fkey', 'mail_account', ['account_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.Enum('new', 'scanned', 'drafted', 'sent', 'quarantined', 'skipped', name='status_types', schema='vat_verification'),
               type_=postgresql.ENUM('new', 'scanned', 'drafted', 'sent', 'quarantined', 'skipped', name='status_types'),
               existing_nullable=True)
        batch_op.drop_column('references')
        batch_op.drop_column('in_reply_to')

    with op.batch_alter_table('mail_draft', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('mail_draft_message_id_fkey', 'mail_message', ['message_id'], ['id'])
        batch_op.create_foreign_key('mail_draft_account_id_fkey', 'mail_account', ['account_id'], ['id'])
        batch_op.alter_column('suggested_by',
               existing_type=sa.Enum('assistant', 'rule', 'manual', name='suggested_by_types', schema='vat_verification'),
               type_=postgresql.ENUM('assistant', 'rule', 'manual', name='suggested_by_types'),
               existing_nullable=True)

    with op.batch_alter_table('mail_account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('mail_account_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.alter_column('provider',
               existing_type=sa.Enum('gmail', 'outlook', 'imap', name='provider_types', schema='vat_verification'),
               type_=postgresql.ENUM('gmail', 'outlook', 'imap', name='provider_types'),
               existing_nullable=False)

    with op.batch_alter_table('known_counterparty', schema=None) as batch_op:
        batch_op.drop_column('trust_level')
    
    # Удаляем ENUM тип trust_levels
    op.execute("DROP TYPE IF EXISTS vat_verification.trust_levels")

    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('counterparties_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_vat_verification_counterparties_vat_number'))
        batch_op.drop_index(batch_op.f('ix_vat_verification_counterparties_user_id'))
        batch_op.drop_index(batch_op.f('ix_vat_verification_counterparties_country'))
        batch_op.drop_index(batch_op.f('ix_vat_verification_counterparties_company_name'))
        batch_op.create_index('ix_counterparties_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_counterparties_company_name', ['company_name'], unique=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('companies_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_vat_verification_companies_vat_number'))
        batch_op.drop_index(batch_op.f('ix_vat_verification_companies_user_id'))
        batch_op.create_index('ix_companies_vat_number', ['vat_number'], unique=False)
        batch_op.create_index('ix_companies_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('check_results_check_id_fkey', 'verification_checks', ['check_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_vat_verification_check_results_service_name'))
        batch_op.drop_index(batch_op.f('ix_vat_verification_check_results_created_at'))
        batch_op.create_index('ix_check_results_service_name', ['service_name'], unique=False)
        batch_op.create_index('ix_check_results_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('alerts_check_id_fkey', 'verification_checks', ['check_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_vat_verification_alerts_created_at'))
        batch_op.create_index('ix_alerts_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###
