"""Add NIS2 compliance platform tables

Revision ID: 58b7ef54fad9
Revises: 3f35c3e4c94b
Create Date: 2026-04-19 17:06:46.614426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58b7ef54fad9'
down_revision = '3f35c3e4c94b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nis2_bsi_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=False),
    sa.Column('legal_form', sa.String(length=50), nullable=True),
    sa.Column('hrb_number', sa.String(length=50), nullable=True),
    sa.Column('registry_court', sa.String(length=100), nullable=True),
    sa.Column('vat_id', sa.String(length=30), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('annual_revenue_eur', sa.BigInteger(), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('subsector', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('is_affected', sa.Boolean(), nullable=True),
    sa.Column('contacts_json', sa.Text(), nullable=True),
    sa.Column('technical_json', sa.Text(), nullable=True),
    sa.Column('wizard_step', sa.Integer(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['vat_verification.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vat_verification'
    )
    with op.batch_alter_table('nis2_bsi_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vat_verification_nis2_bsi_registrations_user_id'), ['user_id'], unique=False)

    op.create_table('nis2_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('incident_ref', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('affected_systems', sa.Text(), nullable=True),
    sa.Column('affected_data', sa.Text(), nullable=True),
    sa.Column('affected_systems_json', sa.Text(), nullable=True),
    sa.Column('affected_data_categories_json', sa.Text(), nullable=True),
    sa.Column('mitigation_steps', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('impact_summary', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('contained_at', sa.DateTime(), nullable=True),
    sa.Column('eradicated_at', sa.DateTime(), nullable=True),
    sa.Column('recovered_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('fruehwarnung_deadline', sa.DateTime(), nullable=True),
    sa.Column('zwischenmeldung_deadline', sa.DateTime(), nullable=True),
    sa.Column('abschlussbericht_deadline', sa.DateTime(), nullable=True),
    sa.Column('fruehwarnung_sent', sa.Boolean(), nullable=True),
    sa.Column('zwischenmeldung_sent', sa.Boolean(), nullable=True),
    sa.Column('abschlussbericht_sent', sa.Boolean(), nullable=True),
    sa.Column('dsgvo_relevant', sa.Boolean(), nullable=True),
    sa.Column('dpa_notification_required', sa.Boolean(), nullable=True),
    sa.Column('dpa_notification_sent', sa.Boolean(), nullable=True),
    sa.Column('dpa_notification_deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['vat_verification.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_ref'),
    schema='vat_verification'
    )
    with op.batch_alter_table('nis2_incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vat_verification_nis2_incidents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_verification_nis2_incidents_user_id'), ['user_id'], unique=False)

    op.create_table('nis2_isms_interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=True),
    sa.Column('company_profile_json', sa.Text(), nullable=True),
    sa.Column('it_landscape_json', sa.Text(), nullable=True),
    sa.Column('security_level_json', sa.Text(), nullable=True),
    sa.Column('risk_assessment_json', sa.Text(), nullable=True),
    sa.Column('current_phase', sa.Integer(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('requested_docs_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['vat_verification.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vat_verification'
    )
    with op.batch_alter_table('nis2_isms_interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vat_verification_nis2_isms_interviews_user_id'), ['user_id'], unique=False)

    op.create_table('nis2_monitoring_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('scan_frequency', sa.String(length=20), nullable=True),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('next_scan_at', sa.DateTime(), nullable=True),
    sa.Column('last_score', sa.Float(), nullable=True),
    sa.Column('previous_score', sa.Float(), nullable=True),
    sa.Column('alert_on_degradation', sa.Boolean(), nullable=True),
    sa.Column('alert_threshold', sa.Float(), nullable=True),
    sa.Column('alert_email', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['vat_verification.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vat_verification'
    )
    with op.batch_alter_table('nis2_monitoring_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vat_verification_nis2_monitoring_targets_user_id'), ['user_id'], unique=False)

    op.create_table('nis2_suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=False),
    sa.Column('vat_id', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('criticality', sa.String(length=20), nullable=True),
    sa.Column('services_provided', sa.Text(), nullable=True),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('vies_valid', sa.Boolean(), nullable=True),
    sa.Column('sanctions_clear', sa.Boolean(), nullable=True),
    sa.Column('registry_active', sa.Boolean(), nullable=True),
    sa.Column('last_verification_at', sa.DateTime(), nullable=True),
    sa.Column('security_score', sa.Float(), nullable=True),
    sa.Column('has_iso27001', sa.Boolean(), nullable=True),
    sa.Column('has_soc2', sa.Boolean(), nullable=True),
    sa.Column('has_bsi_grundschutz', sa.Boolean(), nullable=True),
    sa.Column('tls_grade', sa.String(length=5), nullable=True),
    sa.Column('last_security_scan_at', sa.DateTime(), nullable=True),
    sa.Column('avv_exists', sa.Boolean(), nullable=True),
    sa.Column('avv_signed_at', sa.Date(), nullable=True),
    sa.Column('avv_review_due', sa.Date(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_factors_json', sa.Text(), nullable=True),
    sa.Column('last_assessment_at', sa.DateTime(), nullable=True),
    sa.Column('verification_results_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['vat_verification.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vat_verification'
    )
    with op.batch_alter_table('nis2_suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vat_verification_nis2_suppliers_user_id'), ['user_id'], unique=False)

    op.create_table('nis2_incident_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('generation_error', sa.Text(), nullable=True),
    sa.Column('generated_by_ai', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('bsi_reference', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['vat_verification.nis2_incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vat_verification'
    )
    with op.batch_alter_table('nis2_incident_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vat_verification_nis2_incident_drafts_incident_id'), ['incident_id'], unique=False)

    op.create_table('nis2_incident_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['vat_verification.nis2_incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vat_verification'
    )
    with op.batch_alter_table('nis2_incident_timeline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vat_verification_nis2_incident_timeline_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_verification_nis2_incident_timeline_timestamp'), ['timestamp'], unique=False)

    op.create_table('nis2_isms_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('bsi_standard_ref', sa.String(length=30), nullable=True),
    sa.Column('nis2_paragraph_ref', sa.String(length=30), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=True),
    sa.Column('generation_error', sa.Text(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_interval_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['vat_verification.nis2_isms_interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['vat_verification.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vat_verification'
    )
    with op.batch_alter_table('nis2_isms_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vat_verification_nis2_isms_documents_user_id'), ['user_id'], unique=False)

    op.create_table('nis2_monitoring_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('scan_type', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('diff_json', sa.Text(), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=True),
    sa.Column('critical_count', sa.Integer(), nullable=True),
    sa.Column('high_count', sa.Integer(), nullable=True),
    sa.Column('medium_count', sa.Integer(), nullable=True),
    sa.Column('low_count', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['vat_verification.nis2_monitoring_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vat_verification'
    )
    with op.batch_alter_table('nis2_monitoring_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vat_verification_nis2_monitoring_scans_target_id'), ['target_id'], unique=False)

    op.create_table('nis2_supplier_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('assessment_type', sa.String(length=30), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('security_score', sa.Float(), nullable=True),
    sa.Column('findings_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assessed_by', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.String(length=20), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['vat_verification.nis2_suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vat_verification'
    )
    with op.batch_alter_table('nis2_supplier_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vat_verification_nis2_supplier_assessments_supplier_id'), ['supplier_id'], unique=False)

    # teamguard tables are managed separately — skip to avoid FK constraint errors
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('alerts_check_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'verification_checks', ['check_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('blog_posts_slug_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_blog_posts_category'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_is_published'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_published_at'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_slug'))
        batch_op.create_index(batch_op.f('ix_vat_verification_blog_posts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_verification_blog_posts_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_verification_blog_posts_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vat_verification_blog_posts_slug'), ['slug'], unique=True)

    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('check_results_check_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'verification_checks', ['check_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('companies_user_id_fkey1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('counterparties_user_id_fkey1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('known_counterparty', schema=None) as batch_op:
        batch_op.alter_column('trust_level',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'vip', name='trust_levels'),
               type_=sa.Enum('low', 'medium', 'high', 'vip', name='trust_levels', schema='vat_verification'),
               existing_nullable=True)

    with op.batch_alter_table('mail_account', schema=None) as batch_op:
        batch_op.alter_column('provider',
               existing_type=postgresql.ENUM('gmail', 'outlook', 'imap', name='provider_types'),
               type_=sa.Enum('gmail', 'outlook', 'imap', name='provider_types', schema='vat_verification'),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('mail_account_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('mail_draft', schema=None) as batch_op:
        batch_op.alter_column('suggested_by',
               existing_type=postgresql.ENUM('assistant', 'rule', 'manual', name='suggested_by_types'),
               type_=sa.Enum('assistant', 'rule', 'manual', name='suggested_by_types', schema='vat_verification'),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('mail_draft_message_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('mail_draft_account_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'mail_message', ['message_id'], ['id'], referent_schema='vat_verification')
        batch_op.create_foreign_key(None, 'mail_account', ['account_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('mail_message', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('new', 'scanned', 'drafted', 'sent', 'quarantined', 'skipped', name='status_types'),
               type_=sa.Enum('new', 'scanned', 'drafted', 'sent', 'quarantined', 'skipped', name='status_types', schema='vat_verification'),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('mail_message_account_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('mail_message_counterparty_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'known_counterparty', ['counterparty_id'], ['id'], referent_schema='vat_verification')
        batch_op.create_foreign_key(None, 'mail_account', ['account_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('mail_rule', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=postgresql.ENUM('auto_reply', 'draft', 'quarantine', 'ignore', name='action_types'),
               type_=sa.Enum('auto_reply', 'draft', 'quarantine', 'ignore', name='action_types', schema='vat_verification'),
               existing_nullable=True)

    with op.batch_alter_table('osint_findings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('osint_findings_scan_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'osint_scans', ['scan_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payments_subscription_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('payments_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='vat_verification')
        batch_op.create_foreign_key(None, 'subscriptions', ['subscription_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('pentesting_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pentesting_logs_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('pentesting_quotas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pentesting_quotas_subscription_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'subscriptions', ['subscription_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('scan_report', schema=None) as batch_op:
        batch_op.alter_column('verdict',
               existing_type=postgresql.ENUM('safe', 'suspicious', 'malicious', name='verdict_types'),
               type_=sa.Enum('safe', 'suspicious', 'malicious', name='verdict_types', schema='vat_verification'),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('scan_report_message_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'mail_message', ['message_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('subscriptions_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('verification_checks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('verification_checks_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('verification_checks_counterparty_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('verification_checks_company_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'counterparties', ['counterparty_id'], ['id'], referent_schema='vat_verification')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='vat_verification')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], referent_schema='vat_verification')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_checks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('verification_checks_company_id_fkey'), 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('verification_checks_counterparty_id_fkey'), 'counterparties', ['counterparty_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('verification_checks_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('subscriptions_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('scan_report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('scan_report_message_id_fkey'), 'mail_message', ['message_id'], ['id'])
        batch_op.alter_column('verdict',
               existing_type=sa.Enum('safe', 'suspicious', 'malicious', name='verdict_types', schema='vat_verification'),
               type_=postgresql.ENUM('safe', 'suspicious', 'malicious', name='verdict_types'),
               existing_nullable=False)

    with op.batch_alter_table('pentesting_quotas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pentesting_quotas_subscription_id_fkey'), 'subscriptions', ['subscription_id'], ['id'])

    with op.batch_alter_table('pentesting_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pentesting_logs_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payments_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('payments_subscription_id_fkey'), 'subscriptions', ['subscription_id'], ['id'])

    with op.batch_alter_table('osint_findings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('osint_findings_scan_id_fkey'), 'osint_scans', ['scan_id'], ['id'])

    with op.batch_alter_table('mail_rule', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.Enum('auto_reply', 'draft', 'quarantine', 'ignore', name='action_types', schema='vat_verification'),
               type_=postgresql.ENUM('auto_reply', 'draft', 'quarantine', 'ignore', name='action_types'),
               existing_nullable=True)

    with op.batch_alter_table('mail_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mail_message_counterparty_id_fkey'), 'known_counterparty', ['counterparty_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('mail_message_account_id_fkey'), 'mail_account', ['account_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.Enum('new', 'scanned', 'drafted', 'sent', 'quarantined', 'skipped', name='status_types', schema='vat_verification'),
               type_=postgresql.ENUM('new', 'scanned', 'drafted', 'sent', 'quarantined', 'skipped', name='status_types'),
               existing_nullable=True)

    with op.batch_alter_table('mail_draft', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mail_draft_account_id_fkey'), 'mail_account', ['account_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('mail_draft_message_id_fkey'), 'mail_message', ['message_id'], ['id'])
        batch_op.alter_column('suggested_by',
               existing_type=sa.Enum('assistant', 'rule', 'manual', name='suggested_by_types', schema='vat_verification'),
               type_=postgresql.ENUM('assistant', 'rule', 'manual', name='suggested_by_types'),
               existing_nullable=True)

    with op.batch_alter_table('mail_account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mail_account_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.alter_column('provider',
               existing_type=sa.Enum('gmail', 'outlook', 'imap', name='provider_types', schema='vat_verification'),
               type_=postgresql.ENUM('gmail', 'outlook', 'imap', name='provider_types'),
               existing_nullable=False)

    with op.batch_alter_table('known_counterparty', schema=None) as batch_op:
        batch_op.alter_column('trust_level',
               existing_type=sa.Enum('low', 'medium', 'high', 'vip', name='trust_levels', schema='vat_verification'),
               type_=postgresql.ENUM('low', 'medium', 'high', 'vip', name='trust_levels'),
               existing_nullable=True)

    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('counterparties_user_id_fkey1'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('companies_user_id_fkey1'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('check_results_check_id_fkey'), 'verification_checks', ['check_id'], ['id'])

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vat_verification_blog_posts_slug'))
        batch_op.drop_index(batch_op.f('ix_vat_verification_blog_posts_published_at'))
        batch_op.drop_index(batch_op.f('ix_vat_verification_blog_posts_is_published'))
        batch_op.drop_index(batch_op.f('ix_vat_verification_blog_posts_category'))
        batch_op.create_index(batch_op.f('ix_blog_posts_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_blog_posts_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_category'), ['category'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('blog_posts_slug_key'), ['slug'])

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('alerts_check_id_fkey'), 'verification_checks', ['check_id'], ['id'])

    op.create_table('teamguard_password_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('sent_via', sa.VARCHAR(length=20), server_default=sa.text("'email'::character varying"), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('sent_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acknowledged', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['teamguard_members.id'], name=op.f('teamguard_password_assignments_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('teamguard_password_assignments_pkey'))
    )
    with op.batch_alter_table('teamguard_password_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teamguard_password_assignments_member_id'), ['member_id'], unique=False)

    op.create_table('teamguard_members',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('teamguard_members_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('access_level', sa.VARCHAR(length=20), server_default=sa.text("'employee'::character varying"), autoincrement=False, nullable=False),
    sa.Column('password_last_changed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('password_rotation_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name='teamguard_members_owner_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='teamguard_members_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('teamguard_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teamguard_members_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('teamguard_password_policy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rotation_days', sa.INTEGER(), server_default=sa.text('90'), autoincrement=False, nullable=False),
    sa.Column('min_length', sa.INTEGER(), server_default=sa.text('12'), autoincrement=False, nullable=False),
    sa.Column('require_uppercase', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('require_digit', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('require_special', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('reminder_days_before', sa.INTEGER(), server_default=sa.text('7'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('teamguard_password_policy_owner_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('teamguard_password_policy_pkey')),
    sa.UniqueConstraint('owner_user_id', name=op.f('teamguard_password_policy_owner_user_id_key'))
    )
    op.create_table('teamguard_security_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('performed_by', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['teamguard_members.id'], name=op.f('teamguard_security_events_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('teamguard_security_events_pkey'))
    )
    with op.batch_alter_table('teamguard_security_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teamguard_security_events_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teamguard_security_events_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teamguard_security_events_created_at'), ['created_at'], unique=False)

    op.create_table('teamguard_phishing_tests',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('teamguard_phishing_tests_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('subject_line', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('template_type', sa.VARCHAR(length=30), server_default=sa.text("'link_click'::character varying"), autoincrement=False, nullable=False),
    sa.Column('tracking_token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('sent_to_member_ids_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name='teamguard_phishing_tests_owner_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='teamguard_phishing_tests_pkey'),
    sa.UniqueConstraint('tracking_token', name='teamguard_phishing_tests_tracking_token_key'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('teamguard_phishing_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teamguard_phishing_tests_tracking_token'), ['tracking_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_teamguard_phishing_tests_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('teamguard_phishing_clicks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clicked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ip_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_agent_snippet', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['teamguard_members.id'], name=op.f('teamguard_phishing_clicks_member_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['teamguard_phishing_tests.id'], name=op.f('teamguard_phishing_clicks_test_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('teamguard_phishing_clicks_pkey'))
    )
    with op.batch_alter_table('teamguard_phishing_clicks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teamguard_phishing_clicks_test_id'), ['test_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teamguard_phishing_clicks_member_id'), ['member_id'], unique=False)

    with op.batch_alter_table('nis2_supplier_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vat_verification_nis2_supplier_assessments_supplier_id'))

    op.drop_table('nis2_supplier_assessments', schema='vat_verification')
    with op.batch_alter_table('nis2_monitoring_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vat_verification_nis2_monitoring_scans_target_id'))

    op.drop_table('nis2_monitoring_scans', schema='vat_verification')
    with op.batch_alter_table('nis2_isms_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vat_verification_nis2_isms_documents_user_id'))

    op.drop_table('nis2_isms_documents', schema='vat_verification')
    with op.batch_alter_table('nis2_incident_timeline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vat_verification_nis2_incident_timeline_timestamp'))
        batch_op.drop_index(batch_op.f('ix_vat_verification_nis2_incident_timeline_incident_id'))

    op.drop_table('nis2_incident_timeline', schema='vat_verification')
    with op.batch_alter_table('nis2_incident_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vat_verification_nis2_incident_drafts_incident_id'))

    op.drop_table('nis2_incident_drafts', schema='vat_verification')
    with op.batch_alter_table('nis2_suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vat_verification_nis2_suppliers_user_id'))

    op.drop_table('nis2_suppliers', schema='vat_verification')
    with op.batch_alter_table('nis2_monitoring_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vat_verification_nis2_monitoring_targets_user_id'))

    op.drop_table('nis2_monitoring_targets', schema='vat_verification')
    with op.batch_alter_table('nis2_isms_interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vat_verification_nis2_isms_interviews_user_id'))

    op.drop_table('nis2_isms_interviews', schema='vat_verification')
    with op.batch_alter_table('nis2_incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vat_verification_nis2_incidents_user_id'))
        batch_op.drop_index(batch_op.f('ix_vat_verification_nis2_incidents_status'))

    op.drop_table('nis2_incidents', schema='vat_verification')
    with op.batch_alter_table('nis2_bsi_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vat_verification_nis2_bsi_registrations_user_id'))

    op.drop_table('nis2_bsi_registrations', schema='vat_verification')
    # ### end Alembic commands ###
