"""Add company profile fields to User model

Revision ID: af13f0999271
Revises: c8560cadc898
Create Date: 2025-10-29 10:02:27.897289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af13f0999271'
down_revision = 'c8560cadc898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_vat_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('company_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('company_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('company_phone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('company_phone')
        batch_op.drop_column('company_email')
        batch_op.drop_column('company_address')
        batch_op.drop_column('company_vat_number')

    # ### end Alembic commands ###
