"""Add user_id to counterparties table

Revision ID: c8560cadc898
Revises: cd954586ac25
Create Date: 2025-10-27 23:58:27.752486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8560cadc898'
down_revision = 'cd954586ac25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_companies_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_companies_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_counterparties_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_counterparties_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('verification_checks', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_verification_checks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_checks_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.drop_constraint('fk_counterparties_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_counterparties_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_companies_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_companies_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
