"""Add OSINT tables

Revision ID: cd954586ac25
Revises: 361def0cfaed
Create Date: 2025-10-18 20:24:22.408820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd954586ac25'
down_revision = '361def0cfaed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('osint_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('osint_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osint_scans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_osint_scans_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_osint_scans_email'), ['email'], unique=False)

    op.create_table('osint_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['osint_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('osint_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osint_findings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_osint_findings_scan_id'), ['scan_id'], unique=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_companies_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_companies_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_counterparties_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_counterparties_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('verification_checks', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_verification_checks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_checks_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.drop_constraint('fk_counterparties_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_counterparties_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_companies_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_companies_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('osint_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osint_findings_scan_id'))
        batch_op.drop_index(batch_op.f('ix_osint_findings_created_at'))

    op.drop_table('osint_findings')
    with op.batch_alter_table('osint_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osint_scans_email'))
        batch_op.drop_index(batch_op.f('ix_osint_scans_domain'))
        batch_op.drop_index(batch_op.f('ix_osint_scans_created_at'))

    op.drop_table('osint_scans')
    # ### end Alembic commands ###
