"""Add website security scanner module (pentesting)

Revision ID: e471e5167b34
Revises: 4d68551a0bb5
Create Date: 2026-01-16 10:45:15.037310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e471e5167b34'
down_revision = '4d68551a0bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint('alerts_check_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'verification_checks', ['check_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.drop_constraint('check_results_check_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'verification_checks', ['check_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_companies_user_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.drop_constraint('counterparties_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('known_counterparty', schema=None) as batch_op:
        batch_op.alter_column('trust_level',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'vip', name='trust_levels'),
               type_=sa.Enum('low', 'medium', 'high', 'vip', name='trust_levels', schema='vat_verification'),
               existing_nullable=True)

    with op.batch_alter_table('mail_account', schema=None) as batch_op:
        batch_op.alter_column('provider',
               existing_type=postgresql.ENUM('gmail', 'outlook', 'imap', name='provider_types'),
               type_=sa.Enum('gmail', 'outlook', 'imap', name='provider_types', schema='vat_verification'),
               existing_nullable=False)
        batch_op.drop_constraint('mail_account_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('mail_draft', schema=None) as batch_op:
        batch_op.alter_column('suggested_by',
               existing_type=postgresql.ENUM('assistant', 'rule', 'manual', name='suggested_by_types'),
               type_=sa.Enum('assistant', 'rule', 'manual', name='suggested_by_types', schema='vat_verification'),
               existing_nullable=True)
        batch_op.drop_constraint('mail_draft_account_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('mail_draft_message_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'mail_message', ['message_id'], ['id'], referent_schema='vat_verification')
        batch_op.create_foreign_key(None, 'mail_account', ['account_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('mail_message', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('new', 'scanned', 'drafted', 'sent', 'quarantined', 'skipped', name='status_types'),
               type_=sa.Enum('new', 'scanned', 'drafted', 'sent', 'quarantined', 'skipped', name='status_types', schema='vat_verification'),
               existing_nullable=True)
        batch_op.drop_constraint('mail_message_counterparty_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('mail_message_account_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'known_counterparty', ['counterparty_id'], ['id'], referent_schema='vat_verification')
        batch_op.create_foreign_key(None, 'mail_account', ['account_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('mail_rule', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=postgresql.ENUM('auto_reply', 'draft', 'quarantine', 'ignore', name='action_types'),
               type_=sa.Enum('auto_reply', 'draft', 'quarantine', 'ignore', name='action_types', schema='vat_verification'),
               existing_nullable=True)

    with op.batch_alter_table('osint_findings', schema=None) as batch_op:
        batch_op.drop_constraint('osint_findings_scan_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'osint_scans', ['scan_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('payments_subscription_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('payments_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subscriptions', ['subscription_id'], ['id'], referent_schema='vat_verification')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('scan_report', schema=None) as batch_op:
        batch_op.alter_column('verdict',
               existing_type=postgresql.ENUM('safe', 'suspicious', 'malicious', name='verdict_types'),
               type_=sa.Enum('safe', 'suspicious', 'malicious', name='verdict_types', schema='vat_verification'),
               existing_nullable=False)
        batch_op.drop_constraint('scan_report_message_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'mail_message', ['message_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('subscriptions_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='vat_verification')

    with op.batch_alter_table('verification_checks', schema=None) as batch_op:
        batch_op.drop_constraint('verification_checks_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('verification_checks_company_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('verification_checks_counterparty_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], referent_schema='vat_verification')
        batch_op.create_foreign_key(None, 'counterparties', ['counterparty_id'], ['id'], referent_schema='vat_verification')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='vat_verification')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_checks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('verification_checks_counterparty_id_fkey', 'counterparties', ['counterparty_id'], ['id'])
        batch_op.create_foreign_key('verification_checks_company_id_fkey', 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key('verification_checks_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('subscriptions_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('scan_report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('scan_report_message_id_fkey', 'mail_message', ['message_id'], ['id'])
        batch_op.alter_column('verdict',
               existing_type=sa.Enum('safe', 'suspicious', 'malicious', name='verdict_types', schema='vat_verification'),
               type_=postgresql.ENUM('safe', 'suspicious', 'malicious', name='verdict_types'),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payments_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('payments_subscription_id_fkey', 'subscriptions', ['subscription_id'], ['id'])

    with op.batch_alter_table('osint_findings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('osint_findings_scan_id_fkey', 'osint_scans', ['scan_id'], ['id'])

    with op.batch_alter_table('mail_rule', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.Enum('auto_reply', 'draft', 'quarantine', 'ignore', name='action_types', schema='vat_verification'),
               type_=postgresql.ENUM('auto_reply', 'draft', 'quarantine', 'ignore', name='action_types'),
               existing_nullable=True)

    with op.batch_alter_table('mail_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('mail_message_account_id_fkey', 'mail_account', ['account_id'], ['id'])
        batch_op.create_foreign_key('mail_message_counterparty_id_fkey', 'known_counterparty', ['counterparty_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.Enum('new', 'scanned', 'drafted', 'sent', 'quarantined', 'skipped', name='status_types', schema='vat_verification'),
               type_=postgresql.ENUM('new', 'scanned', 'drafted', 'sent', 'quarantined', 'skipped', name='status_types'),
               existing_nullable=True)

    with op.batch_alter_table('mail_draft', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('mail_draft_message_id_fkey', 'mail_message', ['message_id'], ['id'])
        batch_op.create_foreign_key('mail_draft_account_id_fkey', 'mail_account', ['account_id'], ['id'])
        batch_op.alter_column('suggested_by',
               existing_type=sa.Enum('assistant', 'rule', 'manual', name='suggested_by_types', schema='vat_verification'),
               type_=postgresql.ENUM('assistant', 'rule', 'manual', name='suggested_by_types'),
               existing_nullable=True)

    with op.batch_alter_table('mail_account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('mail_account_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.alter_column('provider',
               existing_type=sa.Enum('gmail', 'outlook', 'imap', name='provider_types', schema='vat_verification'),
               type_=postgresql.ENUM('gmail', 'outlook', 'imap', name='provider_types'),
               existing_nullable=False)

    with op.batch_alter_table('known_counterparty', schema=None) as batch_op:
        batch_op.alter_column('trust_level',
               existing_type=sa.Enum('low', 'medium', 'high', 'vip', name='trust_levels', schema='vat_verification'),
               type_=postgresql.ENUM('low', 'medium', 'high', 'vip', name='trust_levels'),
               existing_nullable=True)

    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('counterparties_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_companies_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('check_results_check_id_fkey', 'verification_checks', ['check_id'], ['id'])

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('alerts_check_id_fkey', 'verification_checks', ['check_id'], ['id'])

    # ### end Alembic commands ###
